### PR TITLE
Reactivate static libs

### PR DESCRIPTION
**Pull request by ymontmarin**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

If there is no fundamental needs of disabling the statics libs, this PR only reactivate it to solve: https://github.com/conda-forge/qhull-feedstock/issues/18 and in turn allow package that use qhull at build time to compile again (see e.g. https://github.com/conda-forge/hpp-pinocchio-feedstock/pull/29)

### CODE REVIEW

**Comment by ymontmarin** [comment]
@conda-forge-admin, please rerender

**Comment by ymontmarin** [comment]
@xhochy I think it is ready to merge, if it is ok to re-activate de statics libs for downstream package requiring qhull at build time :)

**Review by xhochy — CHANGES_REQUESTED** [review]
The static libs should not be part of the default output and generally static linkage should be avoided, see https://github.com/conda-forge/cfep/blob/main/cfep-18.md If you really need them, make this a multi-output recipe,

**Comment by ymontmarin** [comment]
@conda-forge-admin, please rerender

**Comment by ymontmarin** [comment]
@conda-forge-admin, please rerender

**Comment by xhochy** [comment]
@ymontmarin If you're a bit patient, I can build an alternative later today that separate the dynamic lib out and changes the `run_exports`.

**Comment by ymontmarin** [comment]
@xhochy Sorry, I have been a bit messy in my commits, but this looks to work and be ready for merge. I believe it follows the [CFEP 18](https://github.com/conda-forge/cfep/blob/main/cfep-18.md).

However, if you have any enhancement suggestion I can be patient, of course :)

**Review by xhochy — APPROVED** [review]

**Comment by jorisv** [comment]
The qhull-static package only contains `info` directory.
When adding qhull-static as a dependency, the build is not working (missing Qhull::qhullcpp target).

I will recreate a PR to try to fix that.

**Pull request merged**
