### PR TITLE
Fix export of symbols on Windows

### PR DESCRIPTION
**Pull request by jcarpent**
Related to https://github.com/qhull/qhull/pull/93

Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by jcarpent** [comment]
@wolfv This PR is ready for review. Thanks in advance.

**Comment by jcarpent** [comment]
@conda-forge/help-c-cpp This PR is ready for review and merging

**Comment by jcarpent** [comment]
@Sirokujira Would you have time to review this PR?

**Comment by jcarpent** [comment]
@xhochy Will you have to review this PR? Thanks in advance.

**Comment by xhochy** [comment]
Wouldn't it be more viable to auto-generate this file like we do in r-base https://github.com/conda-forge/r-base-feedstock/blob/e74584ad023e552247fc9451a6ce2e576be2b439/recipe/bld-r-base.bat#L52 ?

**Comment by jcarpent** [comment]
> Wouldn't it be more viable to auto-generate this file like we do in r-base https://github.com/conda-forge/r-base-feedstock/blob/e74584ad023e552247fc9451a6ce2e576be2b439/recipe/bld-r-base.bat#L52 ?

Here the situation is a bit different, in the sense that the `.def` file is used to export the DLL.

**Review by xhochy — APPROVED** [review]

**Pull request merged**
